name: pull-request

on: push

jobs:
  install-compiled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod +x scripts/install.sh
          ./scripts/install.sh
      - run: |
          if command -v deno; then
            echo "Deno is installed."
            deno --version
          else
            echo "Deno installation failed."
            exit 1
          fi
